title:              Carbon Mandal
description:        Sustainability Consulting Company
author:             Carbon Mandal
baseurl:            "/carbon-mandal"
url:                "https://www.carbonmandal.com"
company:             Carbon Mandal LLP

# Social Profiles
email_username: info@carbonmandal.com
twitter_username: Carbon-Mandal
github_username: Carbon-Mandal
facebook_username: Carbon-Mandal
instagram_username: Carbon-Mandal
linkedin_username: Carbon-Mandal

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
